In [2]:
import pandas as pd

In [3]:
flights = pd.read_csv(
    "C:\\Users\\HP\\Desktop\\Downloads\\flights.csv",
    low_memory=False
)

In [4]:
flights.shape

(5819079, 31)

In [5]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 31 columns):
 #   Column               Dtype
---  ------               -----
 0   YEAR                 int64
 1   MONTH                int64
 2   DAY                  int64
 3   DAY_OF_WEEK          int64
 4   AIRLINE              object
 5   FLIGHT_NUMBER        int64
 6   TAIL_NUMBER          object
 7   ORIGIN_AIRPORT       object
 8   DESTINATION_AIRPORT  object
 9   SCHEDULED_DEPARTURE  int64
 10  DEPARTURE_TIME       float64
 11  DEPARTURE_DELAY      float64
 12  TAXI_OUT             float64
 13  WHEELS_OFF           float64
 14  SCHEDULED_TIME       float64
 15  ELAPSED_TIME         float64
 16  AIR_TIME             float64
 17  DISTANCE             int64
 18  WHEELS_ON            float64
 19  TAXI_IN              float64
 20  SCHEDULED_ARRIVAL    int64
 21  ARRIVAL_TIME         float64
 22  ARRIVAL_DELAY        float64
 23  DIVERTED             int64
 24  CANCELLED            int64
 25  CANCELLATION_REASON  object
 26  AIR_SYSTEM_DELAY     float64
 27  SECURITY_DELAY       float64
 28  AIRLINE_DELAY        float64
 29  LATE_AIRCRAFT_DELAY  float64
 30  WEATHER_DELAY        float64
dtypes: float64(16), int64(10), object(5)
memory usage: 1.3+ GB

In [6]:
flights.isnull().sum().sort_values(ascending=False)

CANCELLATION_REASON    5729195
LATE_AIRCRAFT_DELAY    4755640
WEATHER_DELAY          4755640
AIRLINE_DELAY          4755640
AIR_SYSTEM_DELAY       4755640
SECURITY_DELAY         4755640
ELAPSED_TIME            105071
AIR_TIME                105071
ARRIVAL_DELAY           105071
WHEELS_ON                92513
TAXI_IN                  92513
ARRIVAL_TIME             92513
WHEELS_OFF               89047
TAXI_OUT                 89047
DEPARTURE_TIME           86153
DEPARTURE_DELAY          86153
TAIL_NUMBER              14721
SCHEDULED_TIME               6
DESTINATION_AIRPORT          0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
MONTH                        0
ORIGIN_AIRPORT               0
SCHEDULED_DEPARTURE          0
YEAR                         0
SCHEDULED_ARRIVAL            0
DISTANCE                     0
DIVERTED                     0
CANCELLED                    0
dtype: int64

In [7]:
flights.duplicated().sum()

np.int64(0)

In [8]:
flights[['AIRLINE','ORIGIN_AIRPORT','DESTINATION_AIRPORT']].head()

  AIRLINE ORIGIN_AIRPORT DESTINATION_AIRPORT
0      AS            ANC                 SEA
1      AA            LAX                 PBI
2      US            SFO                 CLT
3      AA            LAX                 MIA
4      AS            SEA                 ANC

In [9]:
flights['ORIGIN_AIRPORT'].dtype

dtype('O')

In [10]:
flights['CANCELLED'].value_counts()

CANCELLED
0    5729195
1      89884
Name: count, dtype: int64

In [11]:
flights['DIVERTED'].value_counts()

DIVERTED
0    5803892
1      15187
Name: count, dtype: int64

In [12]:
flights.columns = flights.columns.str.strip()

In [13]:
flights['TAIL_NUMBER'] = flights['TAIL_NUMBER'].fillna('Unknown')

In [14]:
delay_cols = [
    'AIR_SYSTEM_DELAY',
    'SECURITY_DELAY',
    'AIRLINE_DELAY',
    'LATE_AIRCRAFT_DELAY',
    'WEATHER_DELAY'
]

flights[delay_cols] = flights[delay_cols].fillna(0)

In [15]:
flights.isnull().sum().sort_values(ascending=False)

CANCELLATION_REASON    5729195
ELAPSED_TIME            105071
ARRIVAL_DELAY           105071
AIR_TIME                105071
WHEELS_ON                92513
TAXI_IN                  92513
ARRIVAL_TIME             92513
TAXI_OUT                 89047
WHEELS_OFF               89047
DEPARTURE_DELAY          86153
DEPARTURE_TIME           86153
SCHEDULED_TIME               6
TAIL_NUMBER                  0
MONTH                        0
YEAR                         0
DESTINATION_AIRPORT          0
ORIGIN_AIRPORT               0
SCHEDULED_DEPARTURE          0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
DISTANCE                     0
SCHEDULED_ARRIVAL            0
DIVERTED                     0
CANCELLED                    0
AIR_SYSTEM_DELAY             0
SECURITY_DELAY               0
AIRLINE_DELAY                0
LATE_AIRCRAFT_DELAY          0
WEATHER_DELAY                0
dtype: int64

In [16]:
flights[flights['SCHEDULED_TIME'].isnull()]

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
483174,2015,2,1,7,NK,416,N627NK,FLL,IAG,2215,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
619941,2015,2,10,2,NK,416,N632NK,FLL,IAG,2215,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
1720237,2015,4,20,1,NK,174,N630NK,FLL,LGA,1602,...,NaN,NaN,1,0,NaN,0.0,0.0,0.0,0.0,0.0
1820960,2015,4,26,7,NK,720,N614NK,DEN,DFW,2059,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
2031482,2015,5,9,6,NK,324,N620NK,MCO,ACY,2130,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
2034453,2015,5,10,7,NK,368,N534NK,ORD,BWI,825,...,NaN,NaN,0,1,C,0.0,0.0,0.0,0.0,0.0

In [17]:
flights[flights['SCHEDULED_TIME'].isnull()]['CANCELLED'].value_counts()

CANCELLED
1    5
0    1
Name: count, dtype: int64

In [18]:
problem_row = flights[
    (flights['SCHEDULED_TIME'].isnull()) &
    (flights['CANCELLED'] == 0)
]

problem_row

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
1720237,2015,4,20,1,NK,174,N630NK,FLL,LGA,1602,...,NaN,NaN,1,0,NaN,0.0,0.0,0.0,0.0,0.0

In [19]:
flights[['DEPARTURE_DELAY','ARRIVAL_DELAY','AIR_TIME','DISTANCE']].describe()

       DEPARTURE_DELAY  ARRIVAL_DELAY      AIR_TIME      DISTANCE
count     5.732926e+06   5.714008e+06  5.714008e+06  5.819079e+06
mean      9.370158e+00   4.407057e+00  1.135116e+02  8.223565e+02
std       3.708094e+01   3.927130e+01  7.223082e+01  6.077843e+02
min      -8.200000e+01  -8.700000e+01  7.000000e+00  2.100000e+01
25%      -5.000000e+00  -1.300000e+01  6.000000e+01  3.730000e+02
50%      -2.000000e+00  -5.000000e+00  9.400000e+01  6.470000e+02
75%       7.000000e+00   8.000000e+00  1.440000e+02  1.062000e+03
max       1.988000e+03   1.971000e+03  6.900000e+02  4.983000e+03

In [22]:
flights.to_csv(
    "C:\\Users\\HP\\Desktop\\Downloads\\flights_cleaned.csv"
)

AIRLINES DATA

In [24]:
airlines = pd.read_csv("C:\\Users\\HP\\Desktop\\Downloads\\airlines.csv")

In [25]:
airlines.shape

(14, 2)

In [26]:
airlines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   IATA_CODE  14 non-null     object
 1   AIRLINE    14 non-null     object
dtypes: object(2)
memory usage: 356.0+ bytes

In [27]:
airlines.isnull().sum()

IATA_CODE    0
AIRLINE      0
dtype: int64

In [28]:
airlines.duplicated().sum()

np.int64(0)

In [29]:
airlines['IATA_CODE'].nunique()

14

In [30]:
airlines.columns = airlines.columns.str.strip()

airlines['IATA_CODE'] = airlines['IATA_CODE'].str.strip()
airlines['AIRLINE'] = airlines['AIRLINE'].str.strip()

In [31]:
airlines.to_csv(
    "C:\\Users\\HP\\Desktop\\Downloads\\airlines_cleaned.csv"
)

AIRPORTS DATA

In [32]:
airports = pd.read_csv("C:\\Users\\HP\\Desktop\\Downloads\\airports.csv")

In [33]:
airports.shape

(322, 7)

In [34]:
airports.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   IATA_CODE  322 non-null    object
 1   AIRPORT    322 non-null    object
 2   CITY       322 non-null    object
 3   STATE      322 non-null    object
 4   COUNTRY    322 non-null    object
 5   LATITUDE   319 non-null    float64
 6   LONGITUDE  319 non-null    float64
dtypes: float64(2), object(5)
memory usage: 17.7+ KB

In [35]:
airports.duplicated().sum()

np.int64(0)

In [36]:
airports['IATA_CODE'].nunique()

322

In [37]:
airports[
    airports['LATITUDE'].isnull() |
    airports['LONGITUDE'].isnull()
]

,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE
96,ECP,Northwest Florida Beaches International Airport,Panama City,FL,USA,NaN,NaN
234,PBG,Plattsburgh International Airport,Plattsburgh,NY,USA,NaN,NaN
313,UST,Northeast Florida Regional Airport (St. August...,St. Augustine,FL,USA,NaN,NaN

In [38]:
airports.columns = airports.columns.str.strip()

In [39]:
for col in ['IATA_CODE','AIRPORT','CITY','STATE','COUNTRY']:
    airports[col] = airports[col].str.strip()

In [40]:
airports.to_csv(
    "C:\\Users\\HP\\Desktop\\Downloads\\airports_cleaned.csv"
)